# Generated by Django 2.1.15 on 2020-02-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmrifDept',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=50, null=True)),
            ],
            options={
                'db_table': 'EMRIF_DEPT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmrifEquip',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=50, null=True)),
                ('equip_company', models.CharField(blank=True, db_column='EQUIP_COMPANY', max_length=50, null=True)),
                ('equip_name', models.CharField(blank=True, db_column='EQUIP_NAME', max_length=50, null=True)),
                ('equip_number', models.CharField(blank=True, db_column='EQUIP_NUMBER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'EMRIF_EQUIP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmrifError',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=500, null=True)),
                ('content', models.CharField(blank=True, db_column='CONTENT', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'EMRIF_ERROR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmrifLab',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=50, null=True)),
                ('call_number', models.CharField(blank=True, db_column='CALL_NUMBER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'EMRIF_LAB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmrifPc',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'EMRIF_PC',
                'managed': False,
            },
        ),
    ]
