# Generated by Django 2.1.15 on 2020-11-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emrif', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emrifaib',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emrifdept',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emrifequip',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emriferror',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emriflab',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emrifpc',
            options={'managed': False, 'ordering': ['status']},
        ),
    ]
