# Generated by Django 2.1.15 on 2020-03-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emrif', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emrifpc',
            options={'managed': False, 'ordering': ['status']},
        ),
    ]
