# Generated by Django 2.1.15 on 2020-03-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrif', '0002_auto_20200303_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmrifAib',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pid', models.CharField(db_column='PID', max_length=10)),
                ('state_flag', models.CharField(blank=True, db_column='STATEFLAG', max_length=50, null=True)),
                ('created', models.DateTimeField(db_column='created')),
            ],
            options={
                'db_table': 'EMRIFAIB',
                'managed': False,
            },
        ),
    ]
