# Generated by Django 2.1.15 on 2020-11-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emrif', '0003_emrifaib'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emriferror',
            options={},
        ),
    ]
